configuration: Release

environment:
  app_version: '1.9.1'

version: '%app_version%.{build}'

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"	
  assembly_informational_version: "%app_version%"

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

before_build:
  - nuget restore

nuget:
  account_feed: true

build:
  publish_nuget: true
  project: SBSuite.BDDHelper.sln 
  verbosity: minimal

test: off #no test in helper dll

deploy:
  provider: NuGet
  on:
    branch: master
  api_key: 
    secure: KiMrq1Jx5rLhBOlyK7sNXjA2WtKtKFfOjO2yQbvQWFtALIPD0fZw47CCH62SF8My
  artifact: /.*\.nupkg/